import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Avetis le meilleur formateur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossOrigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue,{" "}
          <Link href="/dashboard">
            <a>cliqué pour accéder à la comptabilité !</a>
          </Link>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/SofianeIchou"
          target="_blank"
          rel="noopener noreferrer"
        >
          Github{" "}
          <span className={styles.logo}>
            <Image
              src="/github-2.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
        <a
          href="https://www.linkedin.com/in/sofiane-ichou-a0581b1bb/"
          target="_blank"
          rel="noopener noreferrer"
        >
          linkedin{" "}
          <span className={styles.logo}>
            <Image
              src="/linkedin.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  )
}
